development:
  adapter: mysql2
  encoding: utf8
  database: vote_dev
  username: root
  password: '111111'
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: vote_test
  username: root
  password: '111111'
  pool: 5
  timeout: 5000
